import type { Metadata } from "next";
import { Lora, Poppins } from "next/font/google";
import "./globals.css";
import LandingBar from "@/components/LandingBar";
import Footer from "@/components/Footer";

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
})

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${poppins.variable} antialiased min-h-screen flex flex-col`}
      >
        <div className="flex-1 flex flex-col">
          {children}
        </div>
      <footer className="bg-(--space-brown) text-white py-8">
          <div className="container mx-auto px-6 text-center">
              <p>&copy; 2025 My Book Space. All Rights Reserved to Jennifer :).</p>
          </div>
      </footer>
      </body>
    </html>
  );
}
